### PR TITLE
fix: define props to make kebab props work normal

### LINKED ISSUE #27: Bug: hyphenate props not work
A format like `xx-xx` will not work

```
<Text bg-color="red">Label </Text>
<Box
  :padding="1"
  :margin-x="2"
  width="100%"
  :max-width="100"
  flex-direction="column"
  border-color="yellowBright"
  border-style="round"
></Box>
```

### PR DESCRIPTION
**Pull request by webfansplz**
Closes #27

https://github.com/vuejs/core/blob/main/packages/runtime-core/src/componentProps.ts#L369

We should define props to make Vue transform  it automatically.

### CODE REVIEW

**Comment by webfansplz** [comment]
@posva #28 and this PR both can solve the issue.we can choose one to solved it.

File: packages/core/src/components/Box.ts [hunk 1]
```diff
@@ -51,16 +52,17 @@ export interface TuiBoxProps extends Omit<Styles, 'textWrap'> {
 }
 
 export const TuiBox: FunctionalComponent<TuiBoxProps> = (props, { slots }) => {
+  const normalizedProps = pickBy(props, (value) => value !== undefined)
```
Comment (posva) [inline packages/core/src/components/Box.ts:55]: Let's remove this normalizedProps since it's not needed: just setting `TuiBox.props` is enough to generate the good casing

File: packages/core/src/utils/index.ts [hunk 2]
```diff
@@ -72,5 +72,14 @@ export function getElementFromInstance(
   return (instance?.vnode as VNode<DOMNode, DOMElement> | undefined)?.el
 }
 
+export function pickBy<T extends object>(
```
Comment (posva) [inline packages/core/src/utils/index.ts:75]: let's remove this function, it's also quite expensive due to the different Object.* calls

**Review by posva — CHANGES_REQUESTED** [review]
Nice catch!

File: packages/core/src/components/Box.ts (hunk 1 above)
Comment (webfansplz) [reply packages/core/src/components/Box.ts]: Oh,That's really not a good solution ! I found out why I add it.Because the `display` props `undefined`  is treated as `none` to causing them to not work normal.we can just set the default value as `flex` directly.

**Review by posva — APPROVED** [review]
