### PR TITLE
fix: should update when mount/unmount text component

### LINKED ISSUE #7: `v-if` does't work correctly
## code
```vue
<script lang="ts" setup>

const whatShow = ref('Bar')

onKeyData(['k'],() => {
  whatShow.value = whatShow.value === 'Foo' ? 'Bar' : 'Foo'
  console.log('value changed:',whatShow.value)
})


</script>

<template>
    <Box>
      <Text color="red" v-if="whatShow === 'Foo'">Foo</Text>
      <Text color="green" v-else>Bar</Text>
    </Box>
</template>
```

## Steps:
1. Open [Reproduction](https://codesandbox.io/p/github/yuyinws/my-vue-tui-app/draft/musing-beaver?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A1%7D%5D)
2. Press `K`
3. Watch console, the value `whatShow` has changed but template render is not correct.

### PR DESCRIPTION
**Pull request by webfansplz**
Closes #7

### CODE REVIEW

File: packages/core/src/composables/scheduleUpdate.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import { inject } from '@vue/runtime-core'
+import { scheduleUpdateSymbol } from '../injectionSymbols'
+
+export function useScheduleUpdate() {
+  const scheduleUpdate = inject(scheduleUpdateSymbol)!
+  return {
```
Comment (posva) [inline packages/core/src/composables/scheduleUpdate.ts:6]: Lets keep the inject, it avoid creating extra function calls and objects

File: packages/core/src/components/Text.ts [hunk 2]
```diff
@@ -44,9 +45,18 @@ export const TuiText = defineComponent({
   },
 
   setup(props, { slots }) {
-    const scheduleUpdate = inject(scheduleUpdateSymbol)!
+    const { update } = useScheduleUpdate()
+
+    onMounted(() => {
```
Comment (posva) [inline packages/core/src/components/Text.ts:50]: We cab refactor to onMounted(scheduleUpdate) and the other too

**Review by posva — CHANGES_REQUESTED** [review]

**Review by posva — APPROVED** [review]
👍
